<h1>Itens:</h1>
<?php if($this->item): ?>
<h3><?php echo $this->escapehtml(ucwords($this->item->title)); ?></h3>
<div style="width: 250px;float: left;">
    <?php if($this->item->photo_filename):?>
    <img src="<?php echo $this->item->photo_filename; ?>" />
    <?php else: ?>
         No image
    <?php endif; ?>
 </div>
<div style="width: 400px;float: left;margin: 20px;">
    <b>Contact Details</b>
    <br /><?php echo $this->escapehtml($this->item->contact_name); ?>
    <br /><?php echo $this->escapehtml($this->item->contact_email); ?>
    <br /><?php echo $this->escapehtml($this->item->contact_phone); ?>
    <br /><b>Posting Details:</b>
    <br /><?php echo $this->escapehtml($this->item->date_created); ?>
    <br />Price: <?php echo $this->escapehtml($this->item->price); ?>
    <br />City: <?php echo $this->escapehtml($this->item->city); ?>, <?php echo $this->escapehtml($this->item->country); ?>
    <br />Description:
    <p><?php echo $this->escapehtml($this->item->description); ?></p>
 </div>
<?php else: ?>
No recent posting!
<?php endif; ?>
